### ISSUE TITLE
Cannot push because it has sub-directory.

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/github-actions-bin#8]
This is a bit of a tricky issue. We cannot publish this package now that it has a `.github` actions sub-directory.

```
samuel@koyoko ~/D/a/github-actions-bin (master)> git push aur
Enumerating objects: 24, done.
Counting objects: 100% (24/24), done.
Delta compression using up to 8 threads
Compressing objects: 100% (17/17), done.
Writing objects: 100% (21/21), 4.65 KiB | 2.32 MiB/s, done.
Total 21 (delta 11), reused 0 (delta 0), pack-reused 0
remote: Checking connectivity: 21, done.
remote: error: The following error occurred when parsing commit
remote: error: d89ba824e3bfd64f8d12e86857da42c372498712:
remote: error: the repository must not contain subdirectories
remote: error: hook declined to update refs/heads/master
To ssh://aur.archlinux.org/github-actions-bin.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'ssh://aur.archlinux.org/github-actions-bin.git'
```

@petronny do you have any ideas?

**Comment by ioquatix** [comment]
I also asked on the forum: https://bbs.archlinux.org/viewtopic.php?id=265882

**Comment by petronny** [comment]
We can use the `git subtree` command.
I'll try it.

**Comment by petronny** [comment]
Well, there are good news and bad news.

Good news is that the github action is fully functional now.
This is the commit generated for the latest update.
https://github.com/petronny/github-actions-bin/commit/f39e49a4af78020db9a8cfd74fdd23e9182895ae
And it's also pushed to AUR.
https://aur.archlinux.org/cgit/aur.git/commit/?h=github-actions-bin&id=3ae91b7a9ae161694eb055acaed904876682a024

Bad news is that we now have very complicated conflicts between our repositories.
I can't simply solve it by a rebase since the commit is pushed to AUR 
I think the best solution is just use my fork by a forced push.

**Comment by ioquatix** [comment]
That summary make me laugh.

Yes it's totally good news bad news.

I don't have time to look into it right now so I trust you have it working and did your best.

Thanks for your time and effort. Feel free to close this issue if you are okay with the current solution. We can always revisit it.

**Comment by petronny** [comment]
Hi, I create a new project at [arch4edu/aur-auto-update](https://github.com/arch4edu/aur-auto-update) to automatcially update PKGBUILD on AUR.
And github-actions-bin has been added to it. So the issue is solved.

It can also be used for other packages on AUR. Adding `AutoUpdateBot` as a co-maintainer on AUR and the corresponding [nvchecker](https://github.com/lilydjwg/nvchecker) configuration in [nvchecker.toml](https://github.com/arch4edu/aur-auto-update/blob/main/nvchecker.toml) (you can create a PR for it) then the package will be auto updated.
